@startuml
actor Player
entity WorldServer
entity Gateway
entity OtherServerInCluster
autonumber
== Check server changement ==
Player -> WorldServer: Player moving
WorldServer -> WorldServer: Is a player changing server?


== Notify Other World Server ==
WorldServer -> Gateway: Change Server Request (positionId)

activate Gateway

    Gateway -> Gateway: Check if server is still authenticated
    WorldServer <-- Gateway: (if failure) Authentication failed
        activate WorldServer
        Player <-- WorldServer: (if failure) Authentication failed
        deactivate WorldServer
    Gateway -> Gateway: Generate Token
    Gateway -> OtherServerInCluster: notify new player (token)

    activate OtherServerInCluster
    OtherServerInCluster -> OtherServerInCluster: register new player in waiting list
    WorldServer <- Gateway: Pre-Autentication on other server success(token)
    deactivate OtherServerInCluster

deactivate Gateway
WorldServer -> Player: notify player (give ip/token)

@enduml