@startuml
entity ExternalServer
entity Gateway
collections ServersCluster
database DataServer
autonumber
== Server Autentication ==
ExternalServer -> Gateway: Ask auth, typeserver pwd (for the specific server type)
activate Gateway
Gateway -> Gateway: Is Server can connect ?
Gateway -> DataServer : Is Server auth
activate DataServer
Gateway <- DataServer: Validation
deactivate DataServer
ExternalServer <-- Gateway: (if failure) Authentication failed
Gateway -> Gateway: Add Server in register
Gateway -> ServersCluster: notify new server (ip/port/token)
activate ServersCluster
ServersCluster -> ServersCluster: register new server
Gateway -> Gateway: Generate Token
deactivate ServersCluster
ExternalServer <- Gateway: Autentication success(token)
deactivate Gateway

@enduml